name: MAX Bot

on:
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Получить код бота
        uses: actions/checkout@v4

      - name: Установить Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Установить сертификаты Минцифры
        run: |
          sudo curl -k -L -o /usr/local/share/ca-certificates/russian_trusted_root_ca.crt \
            https://gu-st.ru/content/Other/doc/russian_trusted_root_ca.cer
          sudo update-ca-certificates

      - name: Запустить бота
        env:
          MAX_BOT_TOKEN: ${{ secrets.MAX_BOT_TOKEN }}
        run: |
          python main.py
