name: MAX Bot

on:
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Получить код бота
        uses: actions/checkout@v4

      - name: Установить Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Запустить бота
        env:
          MAX_BOT_TOKEN: ${{ secrets.MAX_BOT_TOKEN }}
        run: |
          python main.py
