name: MAX Bot

on:
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Получить код бота
        uses: actions/checkout@v4

      - name: Установить Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Установить сертификаты
        run: |
          python -m pip install --upgrade pip
          python -m pip install --upgrade certifi
          sudo apt-get update
          sudo apt-get install -y ca-certificates
          sudo update-ca-certificates

      - name: Запустить бота
        env:
          MAX_BOT_TOKEN: ${{ secrets.MAX_BOT_TOKEN }}
          SSL_CERT_FILE: ${{ env.pythonLocation }}/lib/python3.12/site-packages/certifi/cacert.pem
        run: |
          python main.py
